spring.application.name= biblioteca
spring.datasource.url=jdbc:postgresql://dpg-d35vnpruibrs73dl9cg0-a.oregon-postgres.render.com/sistemabancario_k339
spring.datasource.username=sistemabancario_k339_user
spring.datasource.password=pAe85RJJPv2u2qXUdcaTAPtAJkAzjA0e
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.path=/aula/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true